### ISSUE TITLE
Shrink repo size

### ISSUE THREAD

**Issue by makenai** [makenai/robotnik#18]
The repository takes forever to check out. I think it's because it includes the .svn history for blockly. Need to dive in and clean that up so it takes less than forever.

http://blog.gbacon.com/2009/08/git-shrinking-subversion-import.html

**Comment by Resseguie** [comment]
Will this go away with #13 ?

**Comment by makenai** [comment]
It's stuck in the history, but I'm working on it now.

**Comment by makenai** [comment]
I ended up using this to prevent blockly from ever happening: https://rtyley.github.io/bfg-repo-cleaner/

As with time travel, I have no idea what side effects may have happened or how it will affect forks (alternate universe timelines).

Before:

Cloning into 'robotnik'...
remote: Counting objects: 1683, done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 1683 (delta 21), reused 0 (delta 0), pack-reused 1634
Receiving objects: 100% (1683/1683), 26.66 MiB | 1.92 MiB/s, done.
Resolving deltas: 100% (525/525), done.
Checking connectivity... done.

After:

Cloning into 'robotnik'...
remote: Counting objects: 520, done.
remote: Compressing objects: 100% (115/115), done.
remote: Total 520 (delta 49), reused 0 (delta 0), pack-reused 403
Receiving objects: 100% (520/520), 3.51 MiB | 1.27 MiB/s, done.
Resolving deltas: 100% (220/220), done.
Checking connectivity... done.

**Comment by Resseguie** [comment]
I don't know if I screwed up something in git or if it just got confused from this. My solution: just completely delete my forked repo and fork a-fresh.
