### ISSUE TITLE
Replace Ace with CodeMirror

### ISSUE THREAD

**Issue by lynnaloo** [makenai/robotnik#23]
Removing the Ace library from static and adding the CodeMirror npm module to robotnik.js

**Comment by lynnaloo** [comment]
I'm going to merge with #22 before I do a PR for this

**Comment by Resseguie** [comment]
Just for completeness sake, can we document here the reasoning for switching editors? (I don't have much experience with either, so this is partly because I'm curious to learn the pros/cons.)

**Comment by lynnaloo** [comment]
@makenai Did you have any specific preference for one over the other? There is an npm package for CodeMirror which is nice. Googling is showing points in favor of both so I don't know that there's a clear winner.

This is an interesting thread: https://github.com/adobe/brackets/issues/1142

**Comment by BrianGenisio** [comment]
I have a lot of experience with CodeMirror... I use it in my dayjob project.  It is solid.  I don't know anything about Ace, but from my understanding, it is equally solid.

**Comment by Resseguie** [comment]
CodeMirror was used by j5-chrome for the original Chromebots too.

**Comment by monteslu** [comment]
Don't remember why we switched on chromebots, but I'm really liking codemirror
