### ISSUE TITLE
Save state

### ISSUE THREAD

**Issue by makenai** [makenai/robotnik#4]
It would be great if we saved state between sessions, so that if something unexpected happens, people can resume their block / code states. Dragging blocks is tedious, so its not fun to recreate something you lost. This could be saved on the client side using window.name or cookies or html 5 storage. It could also be saved to the filesystem.

**Comment by BrianGenisio** [comment]
Agreed.  This platform has the potential to be a very rich robotics IDE.  Blockly is just one way to write code, but a more advanced, professional interface in addition to Blockly would be awesome.

With that, I think that we should be able to create entire project spaces with multiple files.  All of this would save to the file system.  Every new project has a folder with assets.  These assets would include code snippets, or Blockly layouts, configuration, etc.

And sorry if I am just spewing out my thoughts and assertions here on your project.  I'm in brainstorming mode.  Lots of ideas :)

**Comment by Resseguie** [comment]
Maybe I'm stating the obvious, but looks like blockly supports local storage saving of sessions with just a couple lines of code?
https://developers.google.com/blockly/installation/cloud-storage#local_storage

**Comment by makenai** [comment]
Yay, @BrianGenisio implemented saving of blockly states, and I moved it from filesystem to pouchdb in the last merge.
