### ISSUE TITLE
Autoindent in editor

### ISSUE THREAD

**Issue by makenai** [makenai/robotnik#7]
If this is to become a handy dandy IDE, we should autoindent.

**Comment by Resseguie** [comment]
A potential solutions?
https://github.com/jakiestfu/Behave.js

I did a quick scan through several options, but that one seemed the cleanest at a quick glance. If it just did syntax highlighting.

**Comment by makenai** [comment]
That looks excellent!

**Comment by Resseguie** [comment]
Chromebots currently uses CodeMirror: http://codemirror.net/

**Comment by makenai** [comment]
Looks like the editor autoindents nicely now, and the code formatting issue was addressed in my last merge with js-beautify.
